baseURL: https://nkatsasweb.netlify.app/
languageCode: en-us
title: Portfolio website for Kostis Christodoulou
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      In this page you may find glimpes of my team's work for the Data Analytics course and information about my home country, Greece.
    title: Hello, my name is Nikos. Welcome to my website.
  contact: 
    address:
      - city: Athens
        country: Greece
        street: Patriarchou Ioakim
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: nikoskatsas@notmyemail.com
        title: Email
    enable: yes
    phone:
      - phone: (+30) 210-3213036
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Nikolaos Nektarios Katsanevakis
    enable: yes
    #quicklinks:
     # - alt: HTML5 UP
      #  text: 'Design: '
       # url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/olympiacosfc/
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/nick.katsas
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/nick_katsas/
      - icon: fa-github
        label: GitHub
        url: https://github.com/NKatsanev
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/nickkatsanevakis/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
     # - name: Elements
      #  url: elements.html
    menu: Menu
   # subtitle: By HTML5 Up
    #title: Forty
  tiles:
    enable: yes
    showcase:
      - image: parthenon.jpg
        subtitle: 
        title: Athens' Parthenon
        url: blogs/Parthenon
   #   - image: pic02.jpg
    #    subtitle: Feugiat Amet Tempus
     #   title: Tempus
      #  url: blogs/tempus
      #- image: pic03.jpg
       # subtitle: Lorem Etiam Nullam
        #title: Magna
        #url: blogs/magna
      #- image: pic04.jpg
       # subtitle: Nisl Sed Aliquam
        #title: Ipsum
        #url: blogs/ipsum
      #- image: pic05.jpg
       # subtitle: Ipsum Dolor Sit Amet
        #title: Consequat
        #url: blogs/ipsum
      - image: lbs_logo.jpg
        subtitle: My university
        title: London Business School
        url: blogs/lbs
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
